version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]  # Verifica se a rota /health retorna 200
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - backend  # O frontend depende do backend

networks:
  app-network:
    driver: bridge
